name: PRstats workflow
on:
  pull_request:

jobs:
  prstats:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        env:
          PULL_REQUEST_ID: ${{ github.event.number }}
